---
# tasks file for virtualbox

- name: Add Yum Repository
  yum_repository:
       name: virtualbox
       description: VirtualBox repository
       baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
       state: present
  when: ansible_distribution == 'Fedora'
  become: true
