---
# tasks file for virtualbox

- name: Add VirtualBox Repository
  yum_repository:
       name: virtualbox
       description: VirtualBox repository
       baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
       state: present
  when: ansible_distribution == 'Fedora'
  become: yes

- name: Install VirtualBox Dependencies
  package: name={{item}} state=installed
  become: yes
  with_items:
  - binutils
  - gcc
  - make
  - patch
  - libgomp
  - glibc-headers
  - glibc-devel
  - kernel-headers
  - kernel-devel
  - dkms
  when: ansible_distribution == 'Fedora'
